server:
  port: 8082

app:
  kafka:
    topic:
      parking-garage: parking-garage
      parking-events: parking-events

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info,metrics

spring:
  application:
    name: parking-garage-data-generator
  config:
    activate:
      on-profile: cc
    import: file:${user.home}/tools/parking-garage-app-cc.properties

  kafka:
    bootstrap-servers: ${CC_BROKER}
    schema-registry:
      url: ${CC_SCHEMA_REGISTRY_URL}
    properties:
      "[sasl.mechanism]": "PLAIN"
      "[sasl.jaas.config]": org.apache.kafka.common.security.plain.PlainLoginModule required username='${KAFKA_KEY_ID}' password='${KAFKA_KEY_SECRET}';
      "[schema.registry.url]": ${CC_SCHEMA_REGISTRY_URL}
      "[basic.auth.credentials.source]": "USER_INFO"
      "[basic.auth.user.info]": "${SCHEMA_REGISTRY_KEY_ID}:${SCHEMA_REGISTRY_KEY_SECRET}"
      "[auto.register.schemas]": true
      "[client.dns.lookup]": "use_all_dns_ips"
      "[security.protocol]": "SASL_SSL"

#    consumer:
#      group-id: "spring-kafka-cc"
#      auto-offset-reset: earliest
#      key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
#      value-deserializer: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
#      security:
#        protocol: "SASL_SSL"
#      properties:
#        "[specific.avro.reader]": true
